# Setup
title:        Defol_
tagline:      Available on the App Store
baseurl:      "/defol"
locale:       "en"

# About/contact
author:
  name:       Defol_
  url:        https://defolapp.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown